site_name: TB4 Manipulation Pipeline
site_url: https://dghiya.github.io/TB4_Project/

theme:
  name: material
  features:
    - navigation.tabs # Adds top-level tabs if you want them
    - search.suggest  # Auto-suggests results in the search bar

nav:
  - Home: index.md
  - Navigation: navigation.md
  - Perception: perception.md
  - Manipulation: manipulation.md